### ISSUE TITLE
Force-Touch Search

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-ios#1057] opened 2017-08-12 14:21 UTC
The following Tweet can be found [here](https://twitter.com/GGnall/status/896364519928332289):

> **Graham Gnall 🙇 (@GGnall)**
> Feature request: force touch search on @brave iOS app. Would be default search in a heart beat
>
> ![image](https://user-images.githubusercontent.com/815158/29241379-1c3dc472-7f3e-11e7-911d-e0e616fb30fc.png)

For comparison, here is what the user sees when doing the same action on Chrome, Firefox Focus, and Safari:

![image](https://user-images.githubusercontent.com/815158/29241438-81d2f392-7f3f-11e7-8d7e-4fb026d3aad5.png)

**Comment by srirambv** [comment] 2017-08-14 07:16
Should be covered by #814

Also list of features to be included for force touch are #866 #867

**Comment by srirambv** [comment] 2017-08-14 07:17
Closing as dupe of #814

**Closed by srirambv** 2017-08-14 07:17 UTC
Labels: enhancement
