### ISSUE TITLE
tab not highlighted after opening app from background

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1288] opened 2017-11-02 17:42 UTC
### Description:
When open the app from background, the active tab is not in focus on the tab bar.

### Steps to Reproduce

  1. Open a few tabs, any tab can be the active tab.
  2. Background the app for >5 s
  3. Reopen Brave

**Actual result:**
tab which was active is not highlighted/in focus in the tab bar (should be the second tab in this screenshot) - all tabs look the same on the tab bar:
![img_0092](https://user-images.githubusercontent.com/28145373/32341247-4e061e5c-bfd3-11e7-8d49-aea7a7f6aa12.PNG)

**Expected result:**
tab which was active should be in focus/highlighted on the tab bar as it is here:
![img_0093](https://user-images.githubusercontent.com/28145373/32341259-5fa95908-bfd3-11e7-9a92-5759133e1b8d.PNG)

**Reproduces how often:** [Easily reproduced/Intermittent issue] easily reproduced

**Brave Version:**
1.5 (17.11.02.08)

**Device details:**
iPad iOS 10

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Does not reproduce in released version (1.4.2 (17.09.08.16))

**Comment by LaurenWags** [comment] 2017-11-03 18:26
Isn't consistently fixed on iPad iOS10 - sometimes tab is highlighted/in focus when opening app from background and sometimes it's not.

**Comment by srirambv** [comment] 2017-11-03 19:52
Reproed on 1.5(17.11.03.09) on iPad (iOS 11)

**Comment by kjozwiak** [comment] 2017-11-03 21:06
I believe this is only reproducible on the iPads and is working on the iPhones. I couldn't reproduce the issue with an iPhone 6 using iOS10 but easily reproduced the issue with a iPad Mini 4 with iOS11 using ` 1.5(17.11.03.09)`.

**Comment by srirambv** [comment] 2018-04-25 16:27
Looks fixed on iOS 11.3

**Closed** 2018-04-25 18:07 UTC
Labels: QA please, QA/Steps-specified, bug, feature/tabs, good first issue, iPad Specific
