### ISSUE TITLE
Added bookmark accessible after kill and restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#984] opened 2017-07-24 13:26 UTC
- Did you search for similar issues before submitting this one?
Yes

- Description:
Added bookmark accessible after kill and restart

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4 (17.07.20.16)

- Steps to reproduce:
    1. Clean install beta build
    2. Add a bookmark, open a new tab tap on added bookmark, doesn't load
    3. Close, kill and restart app, tap on bookmark, page loads

- Actual Behavior
Added bookmark accessible after kill and restart

- Expected Behavior
Should load when bookmark is opened

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment] 2017-07-26 21:10
Not able to reproduce on (17.07.20.16)

**Comment by jhreis** [comment] 2017-07-27 14:59
Related: #983

**Comment by jhreis** [comment] 2017-07-27 14:59
Should be fixed per: 9a8f179

**Closed by jhreis** 2017-07-27 14:59 UTC
Labels: bug, feature/bookmarks, QA/Steps-specified, regression, release-blocking, swift3
