### ISSUE TITLE
Google Search Sponsored Ads  

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-ios#114] opened 2016-02-03 23:07 UTC
Can't open/click on Google Search Sponsored Ads while Ad Blocked is enabled.  When disabling Ad Blocking, the links work fine.

**Comment by garvankeeley** [comment] 2016-02-03 23:11
Thanks for report, confirmed, should be due to this:
https://github.com/bbondy/abp-filter-parser-cpp/issues/19

**Comment by garvankeeley** [comment] 2016-02-08 16:10
Fixed by  	7bc8aa1
Which led to this:
https://github.com/brave/browser-ios/issues/121
Which is also fixed :)

**Closed by garvankeeley** 2016-02-08 16:10 UTC
Labels: bug
