### ISSUE TITLE
Leaving private mode causes ctd

### ISSUE THREAD

**Issue by toddself** [brave/browser-ios#880] opened 2017-05-27 04:25 UTC
Description:
Exiting private browsing causes a crash to desktop

**Did you search for similar issues before submitting this one?**
Yes
**Expected behavior:**
Not to crash
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6S
- Brave Version:
1.3.3 17.05.10.14
- Steps to reproduce:
    1. Have site open, 
    1. open link on site with long tap and "open link in private browsing"
    2. Tap tab icon
    3. Close private tab
    4. Toggle off private toggle
    5. Crash to desktop

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?
Happens on all sites
- Screenshot if needed:

- Any related issues:

**Comment by toddself** [comment] 2017-05-27 04:26
Also see #878

**Comment by jhreis** [comment] 2017-05-30 13:16
Want to clarify, this is the Brave iOS repo, just want to verify this is a mobile issue, and not a Brave Desktop issue.

**Comment by toddself** [comment] 2017-05-30 21:14
yes.  iphone 6S, brave for iOS

**Comment by wagamama** [comment] 2017-06-03 02:13
This issue also happens on iPhone 6 with Brave version 1.3.3 (17.05.10.13). But I could not reproduce it on Simulator with repo master.

**Comment by jhreis** [comment] 2017-08-11 13:53
This should be fixed in 1.4. Reopen on release if the issue persists.

**Closed by jhreis** 2017-08-11 13:53 UTC
Labels: crash, priority/high
