### ISSUE TITLE
brave crashing when attempting running into HTTP 400 error

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-ios#1516] opened 2018-04-18 18:40 UTC
During the Barrons/MW launch, we ran into an issue where the subscription page wasn't being loaded because of a `This page isn't working HTTP 400` errors which cause `1.5.6 (18.04.11.13)` to crash.

### Steps to Reproduce

STR will be hard to reproduce as it involved an issue with the referral promo but @iccub also reproduced this issue so I'm sure he'll be able to reproduce it locally.

**Actual result:**

**Expected result:**

Brave crashes when attempting to load a `HTTP 400` error.

**Reproduces how often:** [Easily reproduced/Intermittent issue]

Brave should load the page and display an `HTTP 400` error.

**Brave Version:**

* `Brave 1.5.6 (18.04.11.13)`

**Device details:**

Happened on iOS 10.3.3, iOS 11.3 on all the devices.

**Comment by iccub** [comment] 2018-04-19 17:53
This was actually caused by incorrectly parsing header values. Created a separate issue here https://github.com/brave/browser-ios/issues/1528 and closing this one.

**Closed by iccub** 2018-04-19 17:53 UTC
Labels: bug, crash
