### ISSUE TITLE
Unable to access current page after not using for a while

### ISSUE THREAD

**Issue by jkup** [brave/browser-ios#644] opened 2017-01-06 21:57 UTC
Description:

**Did you search for similar issues before submitting this one?**
Yes.

**Expected behavior:**
This may well just be me not understanding how to use the browser but after I don't use the app for a few hours, when I go back I can see the title of the page I was on but I'm not sure how to actually get back to it (screenshot attached). Is this desired behavior? Is there a way to get back to that page?

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone6

- Brave Version:
1.2.19 (16.12.29.17)

- Steps to reproduce:
    1. Go to any page (google.com)
    2. Close the app for a few hours 
    3. Open it back up again and try to access the page

** Website problems only:
- did you check with Brave Shields down?
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)?

- Screenshot if needed:

![img_4745](https://cloud.githubusercontent.com/assets/490294/21734395/00bf8964-d418-11e6-86c0-e3335384e054.PNG)

- Any related issues:

**Comment by garvankeeley** [comment] 2017-01-06 22:05
We had a similar comment about this on twitter. We need to figure out how to repro. Obviously, this be a bad bug.

**Comment by garvankeeley** [comment] 2017-01-06 22:06
Well, I suppose you could be on the tab overview page, if you tap on that tab (to leave the Tab Tray view), is there a 'Cancel' button in the upper right?

**Comment by jkup** [comment] 2017-01-06 22:07
@garvankeeley sorry that picture is misleading.. even on the regular page I just can't see how to get to my site.

**Comment by jkup** [comment] 2017-01-06 22:10
Another possibly related bug is if you open a page (github.com) on brave and then swipe to kill it (double tap home button and then swipe up ((I don't know fancy iOS lingo!))) then when you open Brave again it forgets what page you had open. Chrome remembers. Could that be the same thing?

**Comment by jhreis** [comment] 2017-01-06 22:41
@jkup, Sounds like the same thing. If the app is idle for awhile, and more apps are opened, Brave will eventually be removed from memory (similar to the force quit you described). Seems like it is not properly recovering from this. I can reproduce this quite consistently.

**Comment by garvankeeley** [comment] 2017-01-06 23:05
Tab restore code is the culprit. I am giving this a 'Top Bug' label, and marking for next release, this is important to squish soon.

**Comment by garvankeeley** [comment] 2017-01-06 23:07
BTW, if the app is alive for less than 10 seconds (from cold boot that is), then on next app boot, it will not attempt to restore tabs to avoid a bad tab causing a boot crash loop.

**Comment by garvankeeley** [comment] 2017-01-10 20:50
I would like to get this fixed, by I can't reproduce. I can get the app to unload from memory quite easily on my 5C, and it restores correctly each time.

My method is to load a bunch of memory intensive apps (Dolphin, Safari, iCab, Chrome, Firefox) and load a heavy web page in each one, then switch back to Brave. It restores correctly. The restoration step is easy to see visually, as the page will reload (the app is swapped out of memory, including the webview so restoring the webview requires loading the URL)

**Comment by garvankeeley** [comment] 2017-01-10 20:55
Is it possible that when the app restores, the network down or unstable? (trying to think of what the missing factor is in the repro step)

**Comment by garvankeeley** [comment] 2017-01-10 20:58
@alexwykoff @srirambv have you seen this happen?

**Comment by srirambv** [comment] 2017-01-10 21:23
@garvankeeley I was able to repro this. Like @jkup mentioned I had backgrounded the app for a while. The critical step I guess is to have more apps running in background and Brave is one of the background app running. I was able to repro only when I had more apps running in background along with Brave. With just one or two apps running in background I cannot reproduce the issue.

**Comment by srirambv** [comment] 2017-01-11 16:29
Device lock could be a factor. I am pretty confident when I reproduced the issue the device was locked for a while and after unlocking and opening the app caused the issue.

**Comment by garvankeeley** [comment] 2017-01-11 16:33
Good info! The more clues to this the better.

**Comment by srirambv** [comment] 2017-01-27 09:53
Issue happene d while testing RC build 

Steps performed 
1. visit https://jsfiddle.net/7ke9r14a/9/ 
2. Changed cookie setting and refreshed the page on each change
3. After 4-5 repetition of the above steps got a dead tab, refresh didn't work
4. Closed other tab and navigating back to the original tab loaded the page again

https://www.dropbox.com/s/pwjjpn9jp16esky/WP_20170126_14_22_35_Pro.mp4?dl=0

**Comment by garvankeeley** [comment] 2017-01-27 15:36
Did this trigger the bug more than once?

**Comment by srirambv** [comment] 2017-01-27 16:03
I was able to repro the bug twice with the steps. First time there was just one tab(mentioned in step 1) which is what is captured in the video. Second time I had  3 tabs (the one mentioned in step1, new tab and jsfiddle fingerprint test page). I was able to repro and all 3 tabs were dead but closing the new tab from tab overview and switching back to original tab loaded the page agian

**Comment by garvankeeley** [comment] 2017-01-27 16:13
So I go back and forth from the settings and change the cookie rule? I tried that a few times and reloading the page (using both pull-down and the reload button), but the tab was ok.

**Comment by srirambv** [comment] 2017-01-27 16:17
Yes. Change settings and refresh page on each change.

**Comment by garvankeeley** [comment] 2017-02-06 21:55
We tried a few fixes for this, hopefully it can no longer be repro'd as of latest Beta, I am going to mark this closed for 1.3, and then when/if it happens again, please reopen

**Comment by srirambv** [comment] 2017-02-09 15:09
Issue still not resolved. While testing the new build I had 3 tabs opened first was an new tab. second had google news opened and thrid tab had yahoo opened. After launching the app after a while (around 6hrs) when I try to open a page on the first tab the page was actually loaded in the third tab and the first tab was blank. Pull down refresh on first tab  caused the third tab to reload.
![image](https://cloud.githubusercontent.com/assets/17010094/22788943/69172342-eed9-11e6-98e2-f0eb0d126e4c.png)
![image](https://cloud.githubusercontent.com/assets/17010094/22788961/729cc250-eed9-11e6-9760-17a4033b6e40.png)
![image](https://cloud.githubusercontent.com/assets/17010094/22788967/7b400fb6-eed9-11e6-8ac1-9be90efe55e9.png)

**Comment by srirambv** [comment] 2017-03-04 09:05
Issue easily reproducible when Private only mode is enabled. 
STR:
1. Enable Private only mode from settings
2. Open and video and play it in full screen mode, quit the player and background the app
3. Keep the phone aside for a long time (overnight)
4. Open the app (in morning) and see the dead tab 

First attempt the issue was reproduced within 3 hrs but wasn't consistently able to replicate, but doing the STR and keeping the phone locked overnight able to reproduce it consistently 

![image](https://cloud.githubusercontent.com/assets/17010094/23577512/0016358a-00b9-11e7-9881-92e817014ad1.png)
![image](https://cloud.githubusercontent.com/assets/17010094/23577514/0236bab0-00b9-11e7-9911-b74cbfddc373.png)

**Comment by jhreis** [comment] 2017-04-07 15:15
Should be fixed due to: c089133

**Closed by jhreis** 2017-04-07 15:15 UTC
Labels: Top Bug!
