### ISSUE TITLE
Bookmark title flickers when navigating to a bookmark folder in edit mode

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#461] opened 2016-09-29 17:06 UTC
Description:
Bookmark title flickers when navigating to a bookmark folder in edit mode

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
There should not be any flickering.

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.16(16.09.29.00)

- Steps to reproduce:
    1. Tap on Hamburger menu on top let corner
    2. Tap on Edit at the bottom of screen
    3. Tap on any of the created bookmark folder
    4. Once the it navigates to the folder, the bookmark title bar flickers

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:

**Comment by garvankeeley** [comment] 2016-09-29 20:14
Thanks for filing. Duplicate of #436.

**Closed by garvankeeley** 2016-09-29 20:14 UTC
