### ISSUE TITLE
reports of theguardian.com crashing

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#287] opened 2016-07-12 21:17 UTC
Mention on twitter of http://www.theguardian.com crashing. Trying now to repro, but no luck.

**Comment by jamesmudgett** [comment] 2017-09-13 18:57
Can't reproduce, QA check and close please.

**Comment by Jacalz** [comment] 2017-09-13 19:01
Having a hard time reproducing this, seems to work

**Comment by srirambv** [comment] 2017-09-15 03:34
Works fine on 1.4.2 Closing as not repro

**Closed by srirambv** 2017-09-15 03:34 UTC
Labels: QA please, web compat
