### ISSUE TITLE
user is prompted about browser lock when entering private browsing after browser lock is already enabled

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-ios#1265] opened 2017-10-24 21:40 UTC
### Description:
After you've enabled browser lock and you enter private browsing, you are prompted to enable browser lock again.

### Steps to Reproduce

  1. Navigate to settings.
  2. Set a pin.
  3. Enable browser lock (you are prompted to enter a pin again, but I just navigated back to settings and browser lock was enabled as the switch was orange).
  4. Close settings
  5. Open a tab or two.
  6. Select the tab tray icon and select Private.

**Actual result:**
You receive notification about browser lock functionality asking if you'd like to enable it.

**Expected result:**
I was expecting that I would not receive this notification as I had already enabled in settings. 

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version:
1.5 (17.10.24.14)

### Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPad iOS 10

### Is this an issue in the currently released version?
no

### Is this an issue with Beta build?
yes

### Website problems only: 
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

### Additional Information

cc @srirambv

**Comment by jamesmudgett** [comment] 2017-10-25 19:10
Perhaps this was fixed in latest, not able to reproduce.

**Closed by jamesmudgett** 2017-10-25 19:10 UTC
Labels: bug, feature/browser-lock, feature/private-tabs
