### ISSUE TITLE
Exit private tabs should immediately switch back to source tab 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1531] opened 2018-04-19 19:32 UTC
### Description:
Exit private tabs should immediately switch back to source tab 

### Steps to Reproduce

  1. Open 30 new tab and visit a site on the 30th tab
  2. Long press on a link and open in a new private tab
  3. Open tab container and exit private tab, stays on tabs overview doesn't switch to source tab,  

**Actual result:**
Stays on tabs container view, user needs to scroll down to bottom to go back to  normal tabs.

**Expected result:**
Either switch focus immediately to the source tab or have focus on the source tab position in tabs overview 

**Reproduces how often:** [Easily reproduced/Intermittent issue]
100%

**Brave Version:**
All

**Device details:**
All

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Liunkae** [comment] 2018-05-03 00:45
Duplicate of #1375?

**Comment by jhreis** [comment] 2018-05-03 18:32
@Liunkae looks like it, closing per duplication.

**Closed by jhreis** 2018-05-03 18:32 UTC
Labels: enhancement, feature/private-tabs, feature/tabs, polish, release-notes/exclude
