### ISSUE TITLE
Address bar hidden behind iOS phone header (STR needed)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#352] opened 2016-08-11 05:44 UTC
From support:

> After switching back and forth between onepassword in-app and other tabs, sometimes the address bar would be shifted up and wouldn't come down so I could click on it. It became impossible to use the tab and I would have to completely close the app and reopen it.

**Comment by jamesmudgett** [comment] 2017-09-13 19:05
QA and Close

**Comment by srirambv** [comment] 2017-09-15 03:52
Unable to reproduce based on description. Works fine on 1.4.2 both clean install and upgrade. Closing as DNR

**Closed by srirambv** 2017-09-15 03:52 UTC
Labels: more info needed, QA please
