### ISSUE TITLE
Multiple crash reports on itunes

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1695] opened 2018-08-06 21:29 UTC
There is an increased number of crash reports for 1.6.3 on itunes. Need to investigate the issue. Some crashes reported when using PB only.

**Comment by iccub** [comment] 2018-08-07 08:52
I noticed some today too on my iPad.

**Comment by kjozwiak** [comment] 2018-08-07 22:49
@iccub any updates? Have we figured out what is causing the crashes? Do we know if there's multiple crashes or are these all related to a single issue? Is https://github.com/brave/browser-ios/pull/1696 the main culprit?

Seems like https://github.com/brave/browser-ios/issues/1694 is also affecting a few users.

**Comment by iccub** [comment] 2018-08-08 07:51
@kjozwiak The crash is due to a database race condition and #1696 should fix this. 
I checked Xcode crash logs and all recent crashes are related to the code I fixed in this PR.

**Closed** 2018-08-08 14:59 UTC
Labels: crash, needs investigation, priority/P1

**Comment by srirambv** [comment] 2018-08-13 12:42
@iccub mind adding the test steps for the fix?

**Comment by iccub** [comment] 2018-08-13 12:54
@srirambv 

I was able to reproduce this crash frequently by following steps:
- visit google images
- search for whatever term 'cartoons' or something
- scroll a bit, tap on random image, tap on back arrow to go back
- scroll down a bit and repeat the process
- usually after 5-10 images clicked I was able to make the app crash

The other way I was able to reproduce it to open few links in new tab by long pressing on them, it doesn't crash as often as google images STR. 

I would also do a 10 minutes of browsing random websites test, the crash occurs when navigating to websites.
