### ISSUE TITLE
Favicons doesn't work after update to 1.3.2

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#860] opened 2017-05-06 18:21 UTC
Description:
All favicons got removed when I updated to 1.3.2 and I can't get any new favicons to show if I make new bookmarks 😬
**Did you search for similar issues before submitting this one?**
Yes
**Expected behavior:**
Favicons should work when adding new bookmarks and they should still be visible after the update!
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 5s running iOS 10.3.1
- Brave Version:
1.3.2
- Steps to reproduce:
    1. Add bookmarks
    2. Update to 1.3.2
    3. See that the favicons are gone

- Screenshot if needed:
<a href="http://sv.tinypic.com?ref=2j3peo3" target="_blank"><img src="http://i63.tinypic.com/2j3peo3.png" border="0" alt="Image and video hosting by TinyPic"></a>
Yes I am pretty digged in to brave 😂

**Comment by Jacalz** [comment] 2017-05-06 18:24
When I updated to 1.3.0 The bookmarks totally stoped working so there might be a problem with updating but I don't know 😬 I fixed it with cleaning the whole browser and it would probably work with this issue but it shouldn't happen in the first place 😅

**Comment by Jacalz** [comment] 2017-05-07 12:41
Related https://github.com/brave/browser-ios/issues/853

**Comment by srirambv** [comment] 2017-05-08 18:55
Dupe of #853.

**Closed by srirambv** 2017-05-08 18:55 UTC
