### ISSUE TITLE
Closed tabs get reopened when app is relaunched

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1804] opened 2018-11-12 20:10 UTC
### Description:

Closed tabs get reopened when app is relaunched

### Steps to Reproduce

  1. Install 1.6.6 beta
  2. Visit https://github.com/brave/browser-ios/issues/1799 and go to bravery section
  3. Open all links listed in new tab
  4. Start closing the opened tabs one by one
  5. Remove app from memory and relaunch after 5 secs
  6. All closed tabs gets reopened when browser is relaunched

**Actual result:**
Closed tabs get reopened when app is relaunched

**Expected result:**
Should not reopen closed tabs when app is relaunched

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:**

1.6.6(18.11.09.11)

**Device details:**
iPad (iOS 12)

**Website problems only:**
- did you check with Brave Shields down?

- did you check in Puffin/Dolphin (UIWebView-based browsers)? 

- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment] 2018-11-12 23:31
@srirambv is there a particular way the tabs need to be closed? Using the `X` via the row of tabs? Or closing them via the "Tab Manager"? Do you leave the last page opened or do you remove everything and only leave `about:newtab` opened? I tried a few times but couldn't reproduce on iOS 12 & iOS 10 I might be missing a step.

**Comment by LaurenWags** [comment] 2018-11-13 16:24
I tried reproducing on an iPad with iOS10. I attempted 5 times and got 4 different results. 
Steps:
1. Install 1.6.6 beta
2. On only tab, visit #1799 and go to bravery section (I also bookmarked this page)
3. Long press on each link in this section and open in new tab (note, if a site was listed in two steps, I only opened it once)
4. Tap on the tab immediately to the right of the tab with 1799 and tap on the x to close the tab. 
5. Repeat until all tabs are closed except 1799, leave this one open.
6. Remove app from memory and relaunch after 5 secs

I then saw these results on each of my attempts:
first time, tab with 1799 was gone and replaced with a blank tab
second time, existing tab (showing 1799) was retained and one closed tab was brought back
third time, only existing tab was retained
fourth time, existing tab was retained and two closed tabs were brought back
fifth time, existing tab was retained and two closed tabs were brought back

**Comment by kjozwiak** [comment] 2018-11-13 19:22
This definitely seems like there's some type of issues with how we're storing current tab states and the way we're restoring those saved states when Brave is re-launched.

**Comment by jhreis** [comment] 2018-11-15 22:19
We have reverted much of 1.6.6, so this should not be an issue anymore.

**Closed** 2018-11-15 22:19 UTC
Labels: QA/Steps-specified, bug, feature/tabs, regression, release-blocking

**Comment by kjozwiak** [comment] 2018-11-16 03:55
Went through the above STR several times and couldn't reproduce the original issue. Used several different combinations of the above as well:

* opened a website, closed the same website via the `Tab Toolbar` (repeated for ~10), restarted
* opened several tabs all at once and closed them one by one via the `Tab Toolbar`, restarted
* opened several tabs all at once and closed them one by one via the `Tab Manager`, restarted
* opened several tabs all at once and closed them all at once via the `Tab Manager` button, restarted
