### ISSUE TITLE
Find on page search shows the count next to search term

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#957] opened 2017-07-13 14:41 UTC
- Did you search for similar issues before submitting this one?
Yes

- Description:
Find on page search shows the count next to search term

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)

- Brave Version:
1.4 (17.07.12.19)

- Steps to reproduce:
    1. Open any page 
    2. Tap on the URL bar, tap on `Find on the page`
    3. Enter search term and tap on the up/down arrow
    4. The search count jumps next to the search term
    5. Subsequent search doesn't repeat it

- Actual Behavior
Find on page search shows the count next to search term

- Expected Behavior
Should always show the search count next to the up/down arrow

- Is this an issue with Beta build?
Yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28171856-aef61f40-67e1-11e7-97b3-425a90dc9307.png)

- Any related issues:

**Comment by Jacalz** [comment] 2017-07-27 20:23
Can't reproduce, is this still a bug?

**Comment by cturner35** [comment] 2017-10-03 17:10
Unable to reproduce as well.

**Comment by jhreis** [comment] 2017-10-03 20:57
Closing as a 1.5 milestone so it will be confirmed in next RC testing.

**Closed by jhreis** 2017-10-03 20:57 UTC
Labels: Good first bug, priority/low, QA please, QA/Steps-specified, UX
