### ISSUE TITLE
Swipe left/right to navigate to previous/next page

### ISSUE THREAD

**Issue by PanosSakkos** [brave/browser-ios#180] opened 2016-04-03 00:04 UTC
Firefox for iOS supports this feature as well.

**Comment by benmosher** [comment] 2016-04-11 13:21
duplicate of #2?

**Comment by garvankeeley** [comment] 2016-04-11 13:58
It is, and it is fixed in 1.2.1 which is submitted to the app store

**Closed by garvankeeley** 2016-04-11 13:58 UTC
